name: Build GSSNTLMSSP

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: install dependency
      run: sudo apt-get install libkrb5-dev libunistring-dev gettext xsltproc libxml2-utils docbook-xml  docbook-xsl
    - name: autoreconf
      run: autoreconf -fi
    - name: configure
      run: ./configure --with-wbclient=no
    - name: make
      run: make
    - name: make check
      run: make check
